-- HAPPYAD V613E — SIGNALEMENTS DES PUBLICATIONS PHOTO / VIDEO
-- À exécuter dans Supabase lorsque l'abonnement est renouvelé.
-- Le frontend V613E garde aussi une file locale et réessaie automatiquement.

begin;

create table if not exists public.happyad_post_reports (
  id bigint generated by default as identity primary key,
  post_id text not null,
  reporter_id text not null,
  owner_id text,
  reason text not null,
  details text not null default '',
  source text not null default 'publication',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by text,
  constraint happyad_post_reports_reason_nonempty check (length(btrim(reason)) > 0),
  constraint happyad_post_reports_not_self check (owner_id is null or reporter_id <> owner_id)
);

create index if not exists happyad_post_reports_post_created_idx
  on public.happyad_post_reports (post_id, created_at desc);

create index if not exists happyad_post_reports_reporter_created_idx
  on public.happyad_post_reports (reporter_id, created_at desc);

create unique index if not exists happyad_post_reports_unique_reason_idx
  on public.happyad_post_reports (post_id, reporter_id, reason);

alter table public.happyad_post_reports enable row level security;

drop policy if exists happyad_post_reports_insert_own_v613e
  on public.happyad_post_reports;
create policy happyad_post_reports_insert_own_v613e
on public.happyad_post_reports
for insert
to authenticated
with check (auth.uid()::text = reporter_id);

drop policy if exists happyad_post_reports_select_own_v613e
  on public.happyad_post_reports;
create policy happyad_post_reports_select_own_v613e
on public.happyad_post_reports
for select
to authenticated
using (auth.uid()::text = reporter_id);

revoke all on table public.happyad_post_reports from anon;
grant select, insert on table public.happyad_post_reports to authenticated;

grant usage, select on sequence public.happyad_post_reports_id_seq to authenticated;

commit;
