-- HAPPYAD V820 — Partie 03/03
-- Compteur de vues uniques pour les annonces visibles dans l’Accueil, les résultats ou Annonces.

begin;

create table if not exists public.happyad_listing_views (
  id bigint generated by default as identity primary key,
  listing_id text not null,
  viewer_key text not null,
  viewer_user_id uuid,
  first_source text not null default 'marketplace',
  viewed_at timestamptz not null default now(),
  constraint happyad_listing_views_viewer_key_v820_check check (char_length(viewer_key) between 8 and 190),
  constraint happyad_listing_views_source_v820_check check (first_source in ('home','marketplace','detail','chat_results','video')),
  constraint happyad_listing_views_unique_v820 unique (listing_id,viewer_key)
);

create index if not exists happyad_listing_views_listing_v820_idx
  on public.happyad_listing_views (listing_id,viewed_at desc);

alter table public.happyad_listing_views enable row level security;
revoke all on table public.happyad_listing_views from anon,authenticated;

create or replace function public.happyad_record_listing_view_v1(
  p_listing_id text,
  p_source text default 'marketplace',
  p_viewer_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_listing_id text := trim(coalesce(p_listing_id,''));
  v_source text := lower(trim(coalesce(p_source,'marketplace')));
  v_key text;
  v_inserted boolean := false;
  v_rows integer := 0;
  v_count bigint := 0;
begin
  if char_length(v_listing_id) < 3 then raise exception 'LISTING_ID_INVALID'; end if;
  if v_source not in ('home','marketplace','detail','chat_results','video') then v_source := 'marketplace'; end if;

  if not exists (
    select 1 from public.happyad_posts p
    where p.id::text=v_listing_id
      and coalesce(p.happyad_marketplace,false)=true
      and coalesce(p.listing_status,'active')='active'
      and coalesce(p.is_active,true)=true
      and p.deleted_at is null
  ) then
    raise exception 'LISTING_NOT_ACTIVE';
  end if;

  if v_uid is not null then
    v_key := 'user:'||v_uid::text;
  else
    v_key := regexp_replace(trim(coalesce(p_viewer_key,'')),'[^A-Za-z0-9:_-]','','g');
    if char_length(v_key) < 8 then raise exception 'VIEWER_KEY_REQUIRED'; end if;
    v_key := left(v_key,190);
  end if;

  insert into public.happyad_listing_views(listing_id,viewer_key,viewer_user_id,first_source)
  values(v_listing_id,v_key,v_uid,v_source)
  on conflict (listing_id,viewer_key) do nothing;
  get diagnostics v_rows = row_count;
  v_inserted := v_rows > 0;

  select count(*) into v_count
  from public.happyad_listing_views
  where listing_id=v_listing_id;

  update public.happyad_posts
  set listing_views_count=v_count
  where id::text=v_listing_id;

  return jsonb_build_object(
    'ok',true,
    'listing_id',v_listing_id,
    'count',v_count,
    'new_view',v_inserted,
    'source',v_source
  );
end;
$$;

revoke all on function public.happyad_record_listing_view_v1(text,text,text) from public;
grant execute on function public.happyad_record_listing_view_v1(text,text,text) to anon,authenticated;

commit;

select
  to_regclass('public.happyad_listing_views') is not null as views_table_ok,
  to_regprocedure('public.happyad_record_listing_view_v1(text,text,text)') is not null as views_rpc_ok;
